<?php

use App\Addendumloan;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AddendumloansTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('addendumloans')->delete();

        Addendumloan::create([
            'original_id' => 1,
            'has_addendum' => 1,
            'addendum_type' => 1,
            'applicant_id' => 1,
            'app_date' => '2015-01-01',
            'distributor_approval_date' => '2015-01-14',
            'decision_date' => '2015-01-15',
            'default_due_date' => '2015-12-15',
            'due_date' => '2015-12-15',
            'loan_type_id' => 2,
            'status_id' => 1,
            'crop_year' => '2015',
            'season' => 'S',
            'loc_id' => 5,
            'region_id' => 3,
            'user_id' => 2,
            'farmer_id' => 1,
            'is_cross_collateralized' => 0,
            'is_fast_tracked' => 0,
            'has_attachments' => 1,
            'has_distributor' => 1,
            'distributor_id' => 6,
            'bankruptcy_history' => 1,
            'required_3party' => 1,
            'added_land' => 1,
            'controlled_disbursement' => 0,
            'its_list' => 1,
            'fsa_compliant' => 1,
            'prev_lien_verified' => 1,
            'leases_valid' => 1,
            'bankruptcy_order_received' => 1,
            'received_3party' => 1,
            'recommended' => 1,
            'arm_approved' => 1,
            'dist_approved' => 1,
            'loan_closed' => 1,
            'added_land_verified' => 2,
            'arm_ucc_received' => 1,
            'dist_ucc_received' => 1,
            'aoi_received' => 0,
            'ccc_received' => 0,
            'rebate_assignment' => 0,
            'limit_warning' => 0,
            'crop_inspection' => 0,
            'reconciliation' => 0,
            'grade' => 'B',
            'conditions_asa' => 1,
            'conditions_aci' => 1,
            'conditions_areb' => 1,
            'conditions_afsa' => 1,
            'conditions_adis' => 1,
            'conditions_pg' => 1,
            'conditions_ccl' => 0,
            'conditions_cd' => 0
        ]);

        Addendumloan::create([
            'original_id' => 1,
            'has_addendum' => 1,
            'addendum_type' => 2,
            'applicant_id' => 1,
            'app_date' => '2015-02-01',
            'distributor_approval_date' => '',
            'decision_date' => '2015-01-15',
            'default_due_date' => '2015-12-15',
            'due_date' => '2015-12-15',
            'loan_type_id' => 2,
            'status_id' => 1,
            'crop_year' => '2015',
            'season' => 'S',
            'loc_id' => 5,
            'region_id' => 3,
            'user_id' => 2,
            'farmer_id' => 1,
            'is_cross_collateralized' => 0,
            'is_fast_tracked' => 0,
            'has_attachments' => 1,
            'has_distributor' => 1,
            'distributor_id' => 6,
            'bankruptcy_history' => 1,
            'required_3party' => 1,
            'added_land' => 1,
            'controlled_disbursement' => 0,
            'its_list' => 1,
            'fsa_compliant' => 1,
            'prev_lien_verified' => 1,
            'leases_valid' => 1,
            'bankruptcy_order_received' => 1,
            'received_3party' => 1,
            'recommended' => 1,
            'arm_approved' => 1,
            'dist_approved' => 0,
            'loan_closed' => 0,
            'added_land_verified' => 2,
            'arm_ucc_received' => 1,
            'dist_ucc_received' => 1,
            'aoi_received' => 0,
            'ccc_received' => 0,
            'rebate_assignment' => 0,
            'limit_warning' => 0,
            'crop_inspection' => 0,
            'reconciliation' => 0,
            'grade' => 'B',
            'conditions_asa' => 1,
            'conditions_aci' => 1,
            'conditions_areb' => 1,
            'conditions_afsa' => 1,
            'conditions_adis' => 1,
            'conditions_pg' => 1,
            'conditions_ccl' => 0,
            'conditions_cd' => 0
        ]);
    }
}
