<?php namespace App\Transformers;

use App\Addendumfinancial;
use League\Fractal\TransformerAbstract;

class AddendumfinancialTransformer extends TransformerAbstract {
    public function transform(Addendumfinancial $item)
    {
        //return $item;

        return [
            'id' => $item->id,
            'loan_id' => (integer) $item->loan_id,
            'cpa_financials' => (boolean) $item->cpa_financials,
            'bankruptcy' => (boolean) $item->bankruptcy,
            'judgements' => (boolean) $item->judgements,
            'credit_score' => (double) $item->credit_score,
            'experience' => (double) $item->experience,
            'grade' => $item->grade,
            'amount_requested' => (double) $item->amount_requested,
            'collateral_equipment' => (double) $item->collateral_equipment,
            'collateral_realestate' => (double) $item->collateral_realestate,
            'total_acres' => (double) $item->total_acres,
            'int_percent_arm' => (double) $item->int_percent_arm,
            'int_arm' => (double) $item->int_arm,
            'int_dist' => (double) $item->int_dist,
            'int_other' => (double) $item->int_other,
            'interest' => (double) $item->interest,
            'int_percent_dist' => (double) $item->int_percent_dist,
            'int_percent_other' => (double) $item->int_percent_other,
            'fee_processing_percent' => (double) $item->fee_processing,
            'fee_processing_onTotal' => (boolean) $item->fee_processing_onTotal,
            'proc_fee' => (double) $item->proc_fee,
            'proc_fee_arm_only' => (double) $item->proc_fee_arm_only,
            'fee_service_percent' => (double) $item->fee_service,
            'fee_service_onTotal' => (boolean) $item->fee_service_onTotal,
            'srvc_fee' => (double) $item->srvc_fee,
            'srvc_fee_arm_only' => (double) $item->srvc_fee_arm_only,
            'total_fee_percent' => (double) $item->total_fee_percent,
            'fee_total' => (double) $item->fee_total,
            'total_fsa_payment' => (double) $item->total_fsa_payment,
            'total_claims' => (double) $item->total_claims,
            'total_revenue' => (double) $item->total_revenue,
            'total_balance' => (double) $item->total_balance,
            'remaining_balance' => (double) $item->remaining_balance,
            'balance_paid' => (double) $item->balance_paid,
            'cash_flow' => (double) $item->cash_flow,
            'risk' => (double) $item->risk,
            'risk_adj' => (double) $item->risk_adj,
            'year_1_revenue' => (double) $item->year_1_revenue,
            'year_1_expenses' => (double) $item->year_1_expenses,
            'year_2_revenue' => (double) $item->year_2_revenue,
            'year_2_expenses' => (double) $item->year_2_expenses,
            'year_3_revenue' => (double) $item->year_3_revenue,
            'year_3_expenses' => (double) $item->year_3_expenses,
            'current_assets' => (double) $item->current_assets,
            'current_assets_factor' => (double) $item->current_assets_factor,
            'current_assets_liability' => (double) $item->current_assets_liability,
            'intermediate_assets' => (double) $item->intermediate_assets,
            'intermediate_assets_factor' => (double) $item->intermediate_assets_factor,
            'intermediate_assets_liability' => (double) $item->intermediate_assets_liability,
            'fixed_assets' => (double) $item->fixed_assets,
            'fixed_assets_factor' => (double) $item->fixed_assets_factor,
            'fixed_assets_liability' => (double) $item->fixed_assets_liability,
            'guaranty' => (double) $item->guaranty,
            'debt2asset_ratio' => (double) $item->debt2asset_ratio,
            'debt2asset_ratio_adj' => (double) $item->debt2asset_ratio_adj,
            'ratio_current' => (double) $item->ratio_current,
            'ratio_current_adj' => (double) $item->ratio_current_adj,
            'capWork' => (double) $item->capWork,
            'capWork_adj' => (double) $item->capWork_adj,
            'capBorrow' => (double) $item->capBorrow,
            'capBorrow_adj' => (double) $item->capBorrow_adj,
            'prod' => (double) $item->prod,
            'adj_prod' => (double) $item->adj_prod,
            'disc_prod' => (double) $item->disc_prod,
            'disc_prod_percent' => (double) $item->disc_prod_percent,
            'non_rp_percent' => (double) $item->non_rp_percent,
            'disc_adj_prod' => (double) $item->disc_adj_prod,
            'ins_disc_prod' => (double) $item->ins_disc_prod,
            'disc_ins' => (double) $item->disc_ins,
            'fsa_assignment_percent' => (double) $item->fsa_assignment_percent,
            'disc_ins_percent' => (double) $item->disc_ins_percent,
            'claims_percent' => (double) $item->claims_percent,
            'equipment_percent' => (double) $item->equipment_percent,
            'realestate_percent' => (double) $item->realestate_percent,
            'commit_arm' => (double) $item->commit_arm,
            'commit_dist' => (double) $item->commit_dist,
            'commit_other' => (double) $item->commit_other,
            'commit_total' => (double) $item->commit_total,
            'principal_arm' => (double) $item->principal_arm,
            'principal_dist' => (double) $item->principal_dist,
            'principal_other' => (double) $item->principal_other,
            'principal' => (double) $item->principal,
            'arm_and_dist' => (double) $item->arm_and_dist,
            'collateral' => (double) $item->collateral
        ];
    }
}